version: '2'

project_name: terraform-provider-hostinger

before:
  hooks:
    - go mod tidy

builds:
  - id: hostinger
    main: .
    binary: terraform-provider-hostinger
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: freebsd
        goarch: arm
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    builds:
      - hostinger
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - --batch
      - --yes
      - --armor
      - --detach-sign
      - --local-user
      - "${GPG_FINGERPRINT}"
    cmd: gpg

release:
  github:
    owner: hostinger
    name: terraform-provider-hostinger
  draft: false
  prerelease: false

