name: lint

on:
  pull_request:

permissions:
  pull-requests: read
  contents: read
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58.2
        skip-cache: true
        args: --timeout 5m --verbose
